development:
  adapter: postgresql
  database: sample_app_development
  encoding: unicode
  username: devuser
  password: devuser
  host: localhost

test:
  adapter: postgresql
  database: sample_app_test
  encoding: unicode
  username: devuser
  password: devuser
  host: localhost